version: 1

disable_existing_loggers: True

formatters:
    default:
        format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
    complete:
        datefmt: "%m/%d/%Y %I:%M:%S %p"
        format: "[ %(asctime)s ][ PID %(process)5d ] [ %(filename).7s::%(lineno)-3d ][ %(levelname)5s ] %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: complete
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: complete
        filename: ereg.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    file_handler_only_errors:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: complete
        filename: ereg-errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

loggers:
    ereg:
        level: DEBUG
        handlers: [console, file_handler, file_handler_only_errors]
        propagate: no

root:
    level: WARNING
    handlers: [console, file_handler, file_handler_only_errors]
    propagate: yes
